realm=browserlab.local
fingerprint
lt-cred-mech
use-auth-secret=0
user=browserlab:change-me

listening-ip=0.0.0.0
listening-port=3478
tls-listening-port=5349

min-port=49160
max-port=49200

no-multicast-peers
no-cli
stale-nonce=600
total-quota=100
bps-capacity=0
no-loopback-peers
no-tlsv1
no-tlsv1_1
